### ISSUE TITLE
Create server configuration files

### ISSUE THREAD

**Issue by hauleth** [eriador/orodruin#4]

**Comment by matiangul** [comment]
Found out that Fig has some limits and for now I think I will create base machine, do everything by hand to make it work and package to vagrant box. Later I will create chef recipes as it is started in eriador/sauron

**Comment by matiangul** [comment]
I think we should move this issue to eriador/sauron. Don't you think?

**Comment by matiangul** [comment]
But issue should remain of course

**Comment by hauleth** [comment]
I've already created Fig configuration that works and connect all needed containers. 

--
Łukasz Jan Niemier

Dnia 4 lis 2014 o godz. 08:14 matiangul <notifications@github.com> napisał(a):

**Comment by matiangul** [comment]
Where did you do that? Did you push some containers to docker hub?

**Comment by hauleth** [comment]
Yes. Check out Eriador organization. I've pushed Rails, Heka and Consul. 

--
Łukasz Jan Niemier

Dnia 6 sty 2015 o godz. 22:11 matiangul <notifications@github.com> napisał(a):

**Comment by matiangul** [comment]
I will do this as soon as I am at home. It is in 2 hours
6 sty 2015 23:55 "Łukasz Niemier" <notifications@github.com> napisał(a):

**Comment by hauleth** [comment]
Too late.

**Comment by hauleth** [comment]
Moved to eriador/sauron#1
